[package]
name = "actix"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.11.0"
anyhow = "1.0.98"
serde = "1.0.219"
serde_json = "1.0.140"
solana-client = "2.3.2"
solana-sdk = "2.3.1"
